@echo off
mkdir ..\vs_build
pushd ..\vs_build
cmake -G "Visual Studio 14 2015 Win64" ../blender278/ -DWITH_CYCLES=off -DWITH_AUDASPACE=off -DWITH_ALEMBIC=off -DWITH_OPENAL=off -DWITH_GAMEENGINE=off -DWITH_BUILDINFO=off -DWITH_CODEC_AVI=off -DWITH_CODEC_FFMPEG=off -DWITH_CODEC_SNDFILE=off -DWITH_FFTW3=off -DWITH_GAMEENGINE_DECKLINK=off -DWITH_IK_ITASC=off -DWITH_IMAGE_CINEON=off -DWITH_IMAGE_FRAMESERVER=off -DWITH_IMAGE_OPENEXR=off -DWITH_IMAGE_TIFF=off -DWITH_INPUT_NDOF=off -DWITH_INTERNATIONAL=off -DWITH_OPENCOLLADA=off  -DWITH_OPENCOLORIO=off -DWITH_OPENIMAGEIO=off 
popd


